Repository tgpholly/Revolution, pull requests merged in 2020-01, with the labels that each got.

#7 Add 12 hour time option for console output
  .gitignore
  modules/consoleHelper.js
Labels: size/M

#8 Add Initial startup headers to example request handler
  modules/example_request_handler.js
Labels: size/XS

#11 Resolve async issue
  modules/example_request_handler.js
Labels: size/XS

#12 Remove an unneeded if
  index.js
Labels: size/XS

#13 Package fix
  index.js
Labels: size/XS

#9 Readme updates
  .gitignore
  README.md
Labels: size/S

#14 Package fix again
  index.js
Labels: size/XS

#18 Code order fix
  index.js
Labels: size/S

#16 Add comments to the framework & included modules
  index.js
  modules/consoleHelper.js
  modules/example_request_handler.js
Labels: size/S
